### ISSUE TITLE
add CONTRIBUTING.md file to project 

### ISSUE THREAD

**Issue by satyamkale27** [satyamkale27/c-learning#12]
make a contributing.md file, file should contain how to contribute to this project which includes how to fork,clone,create branch, commit and making pull request.

**Comment by b-tao** [comment]
Hello, I think I can work on this. How can I start?

**Comment by satyamkale27** [comment]
@b-tao you have to create CONTRIBUTING.md file  which consists following things:
1) how to contribute to this project 
2) technical documentation about forking repo, making branch,creating pull request

example of how contributing.md file looks like  https://github.com/Susmita-Dey/Moody/blob/main/CONTRIBUTING.md

**Comment by b-tao** [comment]
Sure thing. Can you assign me this issue and give me permission to push a PR with my changes?

**Comment by satyamkale27** [comment]
Sure, @b-tao  you can make pr

**Comment by b-tao** [comment]
Thank you, I just created a PR with the CONTRIBUTING.md file. Let me know if there are any issues with it.
